### ISSUE TITLE
hello can we learn nlp together?

### ISSUE THREAD

**Issue by HadXu** [MaxPoon/coursera-Advanced-Machine-Learning-specialization#2]
hi, nlp of advanced machine learning is opening, can we learn nlp together? when I do assignment,i hava problems

**Comment by MaxPoon** [comment]
Sure, I haven't started yet, but will probably start soon. You could add me on linkedin or wechat to keep in touch if you want.
Linkedin: https://www.linkedin.com/in/maxpan/
Wechat: maxpanaldo
